 SELECT COALESCE(VB8_FILIAL,  '04') as VB8_FILIAL, VB8_ANO + VB8_MES as DATA,  
 coalesce((select MIN(BZ_PRIENT) from SBZ010 BZ where SUBSTRING(BZ.BZ_FILIAL, 1, 2) IN ('04') AND BZ.BZ_COD = B1_COD 
 AND BZ.BZ_PRIENT != ' ' AND BZ.D_E_L_E_T_ = ' '), '19000101') AS DTADDED,  B1_COD,  B1_QE,  B1_CODFAB,  B1_CODITE, 
  B1_GRUPO,  B1_GROUPC,  B1_PRV1,  B1_LOCPAD,  B1_CONV,  B1_TIPCONV, COALESCE(VL0_PPPJD, '0') VL0_PPPJD,  MAX(LOCACAO) LOCACAO,  
  MAX(BM_PROORI) BM_PROORI,  B5_ISDSHIP,  COALESCE( SUM(VB8_VDAB  ), 0) VB8_VDAB,  COALESCE( SUM(VB8_VDAO  ), 0) VB8_VDAO,  
  COALESCE( SUM(VB8_HITSB ), 0) VB8_HITSB,  COALESCE( SUM(VB8_HITSO ), 0) VB8_HITSO,  COALESCE( SUM(VB8_VDPERB), 0) VB8_VDPERB, 
   COALESCE( SUM(VB8_VDPERO), 0) VB8_VDPERO,  COALESCE( SUM(VB8_HIPERB), 0) VB8_HIPERB,  COALESCE( SUM(VB8_HIPERO), 0) VB8_HIPERO, 
    (    SELECT COALESCE( SUM(B2_QATU), 0) FROM  SB2010 SB2 with(nolock)         JOIN  NNR010 NNR with(nolock)  ON NNR_FILIAL = 
    SUBSTRING(B2_FILIAL, 1, 0) AND NNR_CODIGO = B2_LOCAL AND NNR.NNR_VDADMS = '1' AND NNR.D_E_L_E_T_ = ' '        WHERE 
    SUBSTRING(B2_FILIAL, 1, 2) IN ('04') AND B2_COD = B1_COD AND SB2.D_E_L_E_T_ = ' ' ) QTD_EST ,  (   
         SELECT COALESCE( SUM(C7_QUANT-C7_QUJE), 0) FROM  SC7010 SC7 with(nolock)        WHERE C7_FILIAL = '04' AND C7_PRODUTO = B1_COD 
         AND D_E_L_E_T_ = ' ' AND C7_ENCER = ' ' AND C7_RESIDUO = ' '          AND C7_QUANT > C7_QUJE          
         AND (CASE WHEN B5_ISDSHIP = '1' THEN 'DSHIP' ELSE C7_PEDFAB END) <> ' '    ) QTD_ESTENC        FROM  
         SB1010 SB1 with(nolock)        JOIN RPM_DPE_PARTS ON    FILIAL in ('04') AND PRODUTO    = B1_COD   AND 
         DATAGER = '20250927'        JOIN  SBM010 SBM with(nolock)  ON BM_FILIAL  = '  ' AND B1_GRUPO   = BM_GRUPO 
         AND SBM.D_E_L_E_T_ = ' '        JOIN  SB5010 SB5 with(nolock)  ON B5_FILIAL  = '  ' AND B5_COD     = B1_COD   
         AND SB5.D_E_L_E_T_ = ' '   LEFT JOIN  VB8010 VB8 with(nolock)  ON VB8_FILIAL = '04' AND VB8_PRODUT = B1_COD  
          AND VB8_ANO = '2025' AND VB8_MES = '09' AND VB8.D_E_L_E_T_ = ' '         AND VB8.R_E_C_N_O_ <= 11637826  
          LEFT JOIN  VL0010 VL0 with(nolock)  ON VL0_FILIAL = '  ' AND VL0_CODPEC = B1_COD   AND VL0.D_E_L_E_T_= ' '      
           WHERE SB1.D_E_L_E_T_ = ' '         AND SB1.B1_FILIAL = '  '  GROUP BY COALESCE(VB8_FILIAL,  '04'), VB8_ANO + 
           VB8_MES, B1_COD, B1_QE, B5_ISDSHIP, B1_CODFAB, B1_CODITE, B1_GRUPO, B1_GROUPC, B1_PRV1, B1_LOCPAD, B1_CONV, B1_TIPCONV,
            COALESCE(VL0_PPPJD, '0')  ORDER BY B1_COD 
