 SELECT * 
 FROM (	

 SELECT	'01' QRY,
 	ZA8_PERIOD, ZA8_APROV,
 	ZA8_FILIAL, ZA8_TPORIG, ZA8_CODVEN, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE,
 	ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ZA8_PECORG,
 	ZA8_AGRDIG, '' PERC_COMISSAO, ZA8_PARCCO,'' ZAD_VLBONU, '' ZAD_VLBONP, '' RECZAE,
 	ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA
 FROM	
 	ZA8010 ZA8
 JOIN ZAG010 ZAG 
 ON ZAG_FILIAL = ' '
 AND ZAG_CODVEN = ZA8_CODVEN
 AND ZAG_ATPCOF <> 'S'
 AND ZAG.D_E_L_E_T_ = ' '
 WHERE 
     ZA8_CODVEN  BETWEEN '      ' AND 'ZZZZZZ' AND 
  	ZA8_TPORIG = 'PEC' AND
  	ZA8_IRRIGA <> 'S' AND
  	ZA8_PECORG <> 'O' AND
  	ZA8.D_E_L_E_T_ = ' '
 UNION ALL
 SELECT	'02' QRY,
 	ZA8_PERIOD, ZA8_APROV
 	, ZA8_FILIAL, ZA8_TPORIG, ZAJ_CODVEN 
 	, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE
 	, ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ZA8_PECORG 
 	, ZA8_AGRDIG, '' PERC_COMISSAO, ZA8_PARCCO,'', '', '' 
 	, ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA
 FROM	
 	ZA8010 ZA8
 JOIN ZAJ010 ZAJ
 ON ZAJ_FILIAL = ' ' 
 AND ZAJ_CODVEN = ZA8_CODVEN
 AND ZAJ_CONBOQ = 'S'
 AND ZAJ.D_E_L_E_T_ = ' '
 	JOIN ZAH010 ZAH ON ZAH_CODFIL = ZA8_FILIAL AND ZAJ_CODVEN = ZAH_CODVEN AND ZAH.D_E_L_E_T_ = ' '
 WHERE	
     ZA8_CODVEN  BETWEEN '      ' AND 'ZZZZZZ' AND 
  	ZA8_TPORIG = 'PEC' AND 
  	ZA8_IRRIGA <> 'S'  AND 
  	ZA8_TPOPER <> '98' AND 
  	ZA8_PECORG = 'O'   AND 
 	ZA8.D_E_L_E_T_ = ' ' UNION ALL 

 SELECT	'03' QRY,
 	ZA8_PERIOD, ZA8_APROV
 	, ZA8_FILIAL, ZA8_TPORIG, VAI_CODVEN, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE
 	, ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ''  
 	, '', '' PERC_COMISSAO, ZA8_PARCCO,'', '', '', ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA
 	, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA 
 FROM	
 		ZA8010 ZA8
 		JOIN VAI010 VAI ON VAI_CODTEC = ZA8_CODMEC AND VAI.D_E_L_E_T_ = ' ' 
 		LEFT JOIN ZAM010 ZAM ON VAI_CODVEN = ZAM_CODVEN AND ZAM.D_E_L_E_T_ = ' '
 WHERE	ZA8.D_E_L_E_T_ = ' ' AND
     VAI_CODVEN  BETWEEN '      ' AND 'ZZZZZZ' AND 
  		ZA8_TPORIG = 'SRV' AND
  		ZA8_IRRIGA <> 'S' AND
 			ZAM_REGRA <> '3' AND
			ZA8_COMTEM <> 'N' AND
			ZA8_COMSRV <> 'N'  UNION ALL 
 SELECT '04' QRY,
 		ZA8_PERIOD, ZA8_APROV
 		, ZA8_FILIAL, ZA8_TPORIG, VAI_CODVEN, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE
 		, ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ''  
 		, '', '' PERC_COMISSAO, ZA8_PARCCO,'', '', '', ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA
 		, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA FROM	
 		ZA8010 ZA8
 		JOIN VAI010 VAI ON VAI_CODTEC = ZA8_CODMEC AND VAI.D_E_L_E_T_ = ' ' 
 		LEFT JOIN ZAM010 ZAM ON VAI_CODVEN = ZAM_CODVEN AND ZAM.D_E_L_E_T_ = ' '
 WHERE	ZA8.D_E_L_E_T_ = ' ' AND
     VAI_CODVEN  BETWEEN '      ' AND 'ZZZZZZ' AND   		ZA8_TPORIG = 'SRV' AND
  		ZA8_IRRIGA <> 'S' AND
 			ZAM_REGRA = '3' AND
			ZA8_COMTEM <> 'N' AND
			ZA8_COMSRV <> 'N' AND
			ZA8_COMSLC <> 'N' 
 UNION ALL 
 SELECT	'05' QRY,
 		ZA8_PERIOD, ZA8_APROV
 		, ZA8_FILIAL, ZA8_TPORIG, ZA8_CODVEN, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE
 		, ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ZA8_PECORG 
 		, ZA8_AGRDIG, '' PERC_COMISSAO, ZA8_PARCCO,'', '', ZA8.R_E_C_N_O_, ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM,ZA8_IRRIGA
 		, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA FROM	
 		ZA8010 ZA8
 WHERE	
     ZA8_CODVEN  BETWEEN '      ' AND 'ZZZZZZ' AND   	ZA8_TPORIG = 'CON'
 AND 	ZA8_CODVEN <> '000000'
 AND 	RTRIM(LTRIM((ZA8_PARCCO))) IN ('1','2','3')
 AND 	ZA8.D_E_L_E_T_ = ' '
 UNION ALL 
 SELECT	'06' QRY,
 			ZA8_PERIOD, ZA8_APROV
 			, ZA8_FILIAL, ZA8_TPORIG, ZA8_CODVEN, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE
 			, ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ZA8_PECORG 
 			, ZA8_AGRDIG, '' PERC_COMISSAO, ZA8_PARCCO,'', '', '', ZA8_VALFRE,ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA
 		, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA FROM	
 ZA8010 ZA8
 WHERE	
     ZA8_CODVEN  BETWEEN '      ' AND 'ZZZZZZ' AND  			ZA8_TPORIG = 'SEG'
 AND 		ZA8.D_E_L_E_T_ = ' '
 UNION ALL 
 SELECT DISTINCT	'08' QRY,
 			ZAE_PERIOD, 'S' ZA8_APROV
 			, ZAE_FILIAL, 'VEI', ZAD_VEND, '', ZAD_DTEMIS, ZAD_NF,ZAD_SERIE
 			, ZAD_CLIENT, ZAD_LOJA 
 			,( ROUND( ( 
 						ZAD_BSCOMI / (SELECT SUM(ZAD_BSCOMI) 
 						FROM ZAD010 ZAD2 
 						WHERE ZAD.ZAD_FILORI = ZAD2.ZAD_FILORI AND 
 						ZAD.ZAD_NF = ZAD_NF AND 
 						ZAD.ZAD_SERIE = ZAD2.ZAD_SERIE AND 
 						ZAD2.ZAD_TIPO NOT IN ('I','U') AND 
 						ZAD2.D_E_L_E_T_ = ' ' ) ) 
				* 				ZAE_VALOR ,2) )
 			, 0, '', '' ,ZAD_COMISS PERC_COMISSAO, ''
  		,ZAD_VLBONU, ZAD_VLBONP,   		 ZAD.R_E_C_N_O_ R_E_C_N_O_,   		'' ZA8_VALFRE, '' ZA8_ICMSST, '' ZA8_ITEM, '' ZA8_IRRIGA
 			, '' ZA8_CODCON, '' ZA8_GRPCON, '' ZA8_COTA FROM	
 ZAD010 ZAD
 			JOIN (SELECT ZAE_PERIOD,ZAE_FILIAL, ZAE_NFPROV, ZAE_SRPROV, SUM(ZAE_VALOR) ZAE_VALOR
 				FROM  
 				ZAE010 ZAE
 				WHERE D_E_L_E_T_ = ' '
 				GROUP BY ZAE_PERIOD,ZAE_FILIAL, ZAE_NFPROV, ZAE_SRPROV) ZAE ON ZAE_FILIAL = ZAD_FILORI AND ZAE_NFPROV = ZAD_NF AND ZAE_SRPROV = ZAD_SERIE 
 	JOIN ZAC010 ZAC ON ZAC_PERIOD = ZAE_PERIOD AND ZAC.D_E_L_E_T_ = ' '
 WHERE	
     ZAD_VEND BETWEEN '      ' AND 'ZZZZZZ' AND  		ZAD.D_E_L_E_T_ = ' '
 UNION ALL 
 SELECT	'09' QRY, ZA8_PERIOD, ZA8_APROV, ZA8_FILIAL, 'AGR', ZA8_CODVEN, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE
 			, ZA8_CLIENT, ZA8_LOJA, SUM(ZA8_TOTAL), SUM(ZA8_CUSTO), ZA8_PECORG, ZA8_AGRDIG
 			, CASE WHEN ZA8_TPORIG = 'PEC' THEN ZAO_PRDPER ELSE ZAO_SRVPER END PERC_COMISSAO
 			, ZA8_PARCCO, '', '', '', ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA 
 			, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA FROM	
 		ZA8010 ZA8
 		JOIN ZAO010 ZAO ON ZAO_CODVEN = ZA8_CODVEN AND ZAO.D_E_L_E_T_ = ' '
 WHERE	ZA8_AGRDIG = 'S'
 AND    ZA8_CODVEN  BETWEEN '      ' AND 'ZZZZZZ'  AND 		ZA8_TPORIG <> 'VEI'
 AND		(ZAO_PRDPER > 0  OR ZAO_SRVPER > 0)
 AND 		ZA8_COMTEM <> 'N'
 AND		ZA8_COMSRV <> 'N' 
 AND		ZA8.D_E_L_E_T_ = ' '
 GROUP BY  ZA8_PERIOD,ZA8_APROV,ZA8_FILIAL, ZA8_CODVEN, ZA8_TPORIG,ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE
 			, ZA8_CLIENT, ZA8_LOJA, ZA8_PECORG, ZA8_AGRDIG, ZA8_PARCCO
  		, CASE WHEN ZA8_TPORIG = 'PEC' THEN ZAO_PRDPER ELSE ZAO_SRVPER END, ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA 
 			, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA UNION ALL 
 SELECT '10' QRY,	 ZA8_PERIOD, ZA8_APROV, ZA8_FILIAL, 'AGR', ZA8_CODVEN, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE
 		, ZA8_CLIENT, ZA8_LOJA, ZA8_VLRAMS, ZA8_CUSTO, ZA8_PECORG, ZA8_AGRDIG
 		, ZAO_AMSPER PERC_COMISSAO
 		, ZA8_PARCCO, '', '', '', ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA
 		, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA FROM	
 		ZA8010 ZA8
 		JOIN ZAO010 ZAO ON ZAO_CODVEN = ZA8_CODVEN AND ZAO.D_E_L_E_T_ = ' '
 WHERE	ZA8_VLRAMS > 0
 AND    ZA8_CODVEN  BETWEEN '      ' AND 'ZZZZZZ'  AND		ZAO_AMSPER > 0
 AND		ZA8.D_E_L_E_T_ = ' '
 UNION ALL 
 SELECT	'11' QRY,ZA8_PERIOD, ZA8_APROV,  ZA8_FILIAL, 'AGR', ZA8_CODVEN, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE
 		, ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ZA8_PECORG, ZA8_AGRDIG
 		, ZAO_AMSPER PERC_COMISSAO
 		, ZA8_PARCCO, '', '', '', ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA
 		, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA FROM	
 		ZA8010 ZA8
 		JOIN ZAO010 ZAO ON ZAO_CODVEN = ZA8_CODVEN AND ZAO.D_E_L_E_T_ = ' '
 WHERE	ZA8_TPORIG = 'VEI' 
 AND  ZA8_CODVEN  BETWEEN '      ' AND 'ZZZZZZ'   AND		ZA8_AGRDIG = 'S'
 AND		ZAO_AMSPER > 0
 AND		ZA8.D_E_L_E_T_ = ' '
 UNION ALL 
 SELECT	'12' QRY, 
 		ZA8_PERIOD, ZA8_APROV,  ZA8_FILIAL, 'IRR', ZAP_CODVEN, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE
 		, ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ZA8_PECORG, ZA8_AGRDIG
 		, ZAP_COMISS PERC_COMISSAO
 		, ZA8_PARCCO, '', '', '', ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA
 		, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA FROM	
 		ZA8010 ZA8
 		JOIN ZAH010 ZAH ON ZAH_CODFIL = ZA8_FILIAL AND ZAH.D_E_L_E_T_ = ' '
 		JOIN ZAP010 ZAP ON ZAP_CODVEN = ZAH_CODVEN AND ZAP.D_E_L_E_T_ = ' '
 WHERE	ZA8_IRRIGA = 'S'
 AND    ZA8_CODVEN  BETWEEN '      ' AND 'ZZZZZZ'  AND		ROUND( (1 - (  ( ZA8_CUSTO) + ZA8_ENTICM + ZA8_ENTPIS + ZA8_ENTCOF ) / ZA8_TOTAL )  * 100, 2) between ZAP_MRGDE AND ZAP_MRGATE 
 AND		ZA8.D_E_L_E_T_ = ' '
 UNION ALL 
 SELECT '13' QRY, 		ZA8_PERIOD, ZA8_APROV,  ZA8_FILIAL, 'PEC_RAC', ZAJ_CODVEN, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE  		, ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ZA8_PECORG, ZA8_AGRDIG  		, ZAJ_PRCRAC PERC_COMISSAO  		, ZA8_PARCCO, '', '', '', ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA  		, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA 	FROM  		ZA8010 ZA8
 		JOIN ZAH010 ZAH ON ZAH_CODFIL = ZA8_FILIAL AND ZAH_RAC = 'S' AND ZAH.D_E_L_E_T_ = ' '  		JOIN ZAJ010 ZAJ ON ZAH_CODVEN = ZAJ_CODVEN AND ZAJ.D_E_L_E_T_ = ' '  WHERE      ZA8_CODVEN  BETWEEN '      ' AND 'ZZZZZZ' AND  		ZA8_SITTPO = '1' AND  		ZA8_TPORIG = 'PEC' AND  		ZA8.D_E_L_E_T_ = ' '  UNION ALL 
 SELECT '14' QRY, ZA8_PERIOD, ZA8_APROV,  ZA8_FILIAL, 'SRV_RAC', ZAM_CODVEN, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE  		, ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ZA8_PECORG, ZA8_AGRDIG  		, ZAM_PRCRAC PERC_COMISSAO  		, ZA8_PARCCO, '', '', '', ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA  		, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA 	FROM  		ZA8010 ZA8
 		JOIN ZAH010 ZAH ON ZAH_CODFIL = ZA8_FILIAL AND ZAH_RAC = 'S' AND ZAH.D_E_L_E_T_ = ' '  		JOIN ZAM010 ZAM ON ZAH_CODVEN = ZAM_CODVEN AND ZAM.D_E_L_E_T_ = ' '  WHERE      ZA8_CODVEN  BETWEEN '      ' AND 'ZZZZZZ' AND  		ZA8_SITTPO = '1' AND  		ZA8_TPORIG = 'SRV' AND 		SUBSTRING(ZA8.ZA8_CODSRV,1,3) <> 'CSC' AND SUBSTRING(ZA8.ZA8_CODSRV,1,3) <> 'CSPC'  		AND ZA8.D_E_L_E_T_ = ' '  UNION ALL 
 SELECT '15' QRY,
 ZA8_PERIOD, ZA8_APROV,  ZA8_FILIAL, 'SRV_LAVORO', ZAM_CODVEN, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE 
 		, ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ZA8_PECORG, ZA8_AGRDIG 
 		, ZAM_PERC01 PERC_COMISSAO 
 		, ZA8_PARCCO, '', '', '', ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA 
 		, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA 	FROM 
 		ZA8010 ZA8

 		JOIN ZAH010 ZAH ON ZAH_CODFIL = ZA8_FILIAL AND ZAH.D_E_L_E_T_ = ' ' 
 		JOIN ZAM010 ZAM ON ZAH_CODVEN = ZAM_CODVEN AND ZAM_CSDRGR = 'S' AND ZAM_REGRA = '1' AND ZAM_FUNCAO = '1' AND ZAM.D_E_L_E_T_ = ' ' 
 WHERE 
     ZA8_CODVEN  BETWEEN '      ' AND 'ZZZZZZ' AND  		ZA8_TPORIG = 'SRV' AND 
 		ZA8.D_E_L_E_T_ = ' ' 
 UNION ALL 
 SELECT '16' QRY,
 	ZA8_PERIOD, ZA8_APROV,  ZA8_FILIAL, 'PEC_LAVORO', VAI_CODVEN, VAI_CODVEN, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE 
 		, ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ZA8_PECORG, ZA8_AGRDIG 
 		, ZAJ_PERC02 PERC_COMISSAO 
 		, ZA8_PARCCO, '', '', '', ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA 
 		, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA FROM 
 		ZA8010 ZA8
 	JOIN VAI010 VAI ON VAI_CODTEC = ZA8_CODMEC AND VAI.D_E_L_E_T_ = ' ' 
 	JOIN ZAM010 ZAM ON VAI_CODVEN = ZAM_CODVEN AND ZAM_CSDRGR = 'S' AND ZAM_REGRA = '1' AND ZAM_FUNCAO = '2' AND ZAM.D_E_L_E_T_ = ' ' 
 	JOIN ZAJ010 ZAJ ON VAI_CODVEN = ZAJ_CODVEN AND ZAJ.D_E_L_E_T_ = ' ' 
 WHERE 
     VAI_CODVEN  BETWEEN '      ' AND 'ZZZZZZ' AND  	ZA8_TPORIG = 'PEC' AND 
 	ZA8_PECORG = 'O' AND 
 	ZA8.D_E_L_E_T_ = ' ' 
 UNION ALL 
SELECT	'18' QRY,
 	ZA8_PERIOD, ZA8_APROV
 	, ZA8_FILIAL, ZA8_TPORIG, ZA8_CODVEN 
 	, ZA8_CODMEC, ZA8_DTEMIS, ZA8_NF, ZA8_SERIE
 	, ZA8_CLIENT, ZA8_LOJA, ZA8_TOTAL, ZA8_CUSTO, ZA8_PECORG 
 	, ZA8_AGRDIG, '' PERC_COMISSAO, ZA8_PARCCO,'', '', '' 
 	, ZA8_VALFRE, ZA8_ICMSST, ZA8_ITEM, ZA8_IRRIGA, ZA8_CODCON, ZA8_GRPCON, ZA8_COTA FROM	ZA8010 ZA8	JOIN ZAH010 ZAH 	ON ZAH_CODFIL = ZA8_FILIAL 	AND ZAH_CODVEN = ZA8_CODVEN 	AND ZAH.D_E_L_E_T_ = ' 'WHERE	ZA8_FILIAL BETWEEN '01' AND '33' AND   ZA8_CODVEN NOT IN ('000058','000057','000076','000288','000281','000469','000646','000667','000591','000687','000614','000608','000740','000786','000822','000483','000865','000888','000903','001065','001086','001110','001117','001192','001222','001237','001274','001287','001303','001362','001403','001444','001442','001448','001493','001494','001508','001509','001515','001532','001542','001578','001795','001616','001725','001796','001720','001611','001708','001610','001693','001721','001607','001608','001646','001613','001726','001640','001709','001722','001682','001767','001697','001612','001615','001691','001599','001700','001604','001685','001645','001954','001962','001973','001990','001989','002017','002006') AND  	ZA8_TPORIG = 'PEC' AND 	ZA8_IRRIGA <> 'S'  AND 	ZA8_TPOPER <> '98' AND 	ZA8_PECORG = 'O'   AND	ZA8.D_E_L_E_T_ = ' ' ) ZZ 
 WHERE 
     ZA8_CODVEN  BETWEEN '      ' AND 'ZZZZZZ' AND   ZA8_PERIOD = '202509' AND 
  ZA8_FILIAL BETWEEN '01' AND '33' AND 
  		ZA8_APROV <> 'N' 
