SELECT
	ZL1_CLIENT 'Raiz CNPJ/CPF', 
	( SELECT TOP 1 A1_CGC + ';' + A1_NOME
		FROM SA1010 SA1 WITH (NOLOCK)
		WHERE SA1.D_E_L_E_T_ = ' ' AND A1_MSBLQL <> '1' AND A1_FILIAL = '  ' 
			AND ( ( A1_PESSOA = 'J' AND SUBSTRING(A1_CGC,1,8) = ZL1_CLIENT AND SUBSTRING(A1_CGC,14,1) > ' ' )
				OR ( A1_PESSOA = 'F' AND SUBSTRING(A1_CGC,1,9) = ZL1_CLIENT AND SUBSTRING(A1_CGC,14,1) = ' ' ) )
		ORDER BY 1 ) 'CPF/CNPJ;Nome',
	CASE WHEN ZL1_STATUS = '3' THEN 'CRED REPROVADO' WHEN ZL1_STATUS = '4' THEN 'CRED APROVADO' ELSE ZL1_STATUS END Status,
	CONVERT( VARCHAR, CONVERT( DATE, SUBSTRING( ZL1_DTINC, 1, 8 ) ), 103 ) 'Data',
	ZL1_RISCO 'Risco',
	CONVERT( VARCHAR, CONVERT( DATE, SUBSTRING( ZL1_ULTCOM, 1, 8 ) ), 103 ) 'Ult Compra',
	ZL1_MATR 'Maior Atraso',
	ZL1_QTDDEB 'Qtd Debitos',
	ZL1_VALDEB 'Val Debitos',
	CONVERT( VARCHAR, CONVERT( DATE, SUBSTRING( ZL1_PRIDEB, 1, 8 ) ), 103 ) 'Primeiro Debito',
	ZL1_SCORE 'Score Serasa',
	ZL1_VALSRS 'Valor Serasa',
	CONVERT( VARCHAR, CONVERT( DATE, SUBSTRING( ZL1_DTRAPI, 1, 8 ) ), 103 ) 'Data Consulta',
	ISNULL(CAST(CAST(ZL1_PARECE AS VARBINARY(8000)) AS VARCHAR(8000)),'') AS 'Parecer',
	( SELECT SUM( ZL2_TITP12 ) FROM ZL2010 ZL2 WHERE ZL2.D_E_L_E_T_ = ' ' AND ZL2_FILIAL = ZL1_FILIAL AND ZL2_NUM = ZL1_NUM AND ZL2_GRPNAT IN ('P','S') ) 'Pagtos Ult 12M Pec/Serv',
	( SELECT SUM( ZL2_LCSUG ) FROM ZL2010 ZL2 WHERE ZL2.D_E_L_E_T_ = ' ' AND ZL2_FILIAL = ZL1_FILIAL AND ZL2_NUM = ZL1_NUM AND ZL2_GRPNAT IN ('P','S') ) 'Limite Sugerido Pec/Serv',
	( SELECT MAX( A1_LC )
		FROM SA1010 SA1 WITH (NOLOCK)
		WHERE SA1.D_E_L_E_T_ = ' ' AND A1_MSBLQL <> '1' AND A1_FILIAL = '  ' 
			AND ( ( A1_PESSOA = 'J' AND SUBSTRING(A1_CGC,1,8) = ZL1_CLIENT AND SUBSTRING(A1_CGC,14,1) > ' ' )
				OR ( A1_PESSOA = 'F' AND SUBSTRING(A1_CGC,1,9) = ZL1_CLIENT AND SUBSTRING(A1_CGC,14,1) = ' ' ) ) ) 'Limite Atual'
FROM ZL1010 ZL1 WITH (NOLOCK)
WHERE  ZL1.D_E_L_E_T_= ' ' AND ZL1_FILIAL = '  ' 
	--AND ZL1_CLIENT = '325443320' AND ZL1_SCORE > 0 AND ZL1_DTRAPI >= '20250304'  
ORDER BY  ZL1_CLIENT