SELECT  TOP 250 R_E_C_N_O_ FROM dbo.SE1010 WHERE  E1_FILIAL  > '01' AND D_E_L_E_T_ = ' ' AND (( ( RTRIM(LTRIM(E1_CLIENTE)) = '010005' ) 
OR ( ( RTRIM(LTRIM(E1_CLIENTE)) = '      ' )
 OR ( ( RTRIM(LTRIM(E1_CLIENTE)) = '      ' ) OR ( RTRIM(LTRIM(E1_CLIENTE)) = '      ' ) ) ) ) AND E1_SALDO > 0) 
 ORDER BY E1_FILIAL,E1_PREFIXO,E1_NUM,E1_PARCELA,E1_TIPO,R_E_C_N_O_