SELECT DISTINCT ' ' AS 'ChaveProdutoClasse',B1_COD AS 'ChaveProduto',B1_GRUPO AS 'ChaveClasseDeProduto' FROM SB1010 SB1 , SBM010 SBM 
WHERE  SB1.D_E_L_E_T_<>'*' AND SBM.D_E_L_E_T_<>'*' AND SBM.BM_GRUPO=SB1.B1_GRUPO AND SBM.BM_VAICRM='1' AND SB1.B1_GRUPO NOT IN (' ','VEIC') AND SBM.BM_VAICRM='1' 
AND (EXISTS (SELECT 1 FROM SB2010 SB2 WHERE  SB2.B2_COD=SB1.B1_COD AND SB2.D_E_L_E_T_=' ')  OR EXISTS (SELECT 1 FROM SD1010 SD1 WHERE  SD1.D1_COD=SB1.B1_COD AND DATEDIFF(DD ,
 CONVERT(DATETIME , SD1.D1_DTDIGIT , 103 ) , GETDATE() ) <= 120)  OR EXISTS (SELECT 1 FROM SD2010 SD2 WHERE  SD2.D2_COD=SB1.B1_COD AND SD2.D2_EMISSAO>='20200101')  ) 
 UNION ALL  
 SELECT DISTINCT ' ' AS 'ChaveProdutoClasse',LTRIM(RTRIM(VV1_CODMAR)) + '#' + RTRIM(LTRIM(VV2_MODVEI)) AS 'ChaveProduto',
 'FAM.'+LTRIM(RTRIM(VV1_CODMAR))+'.'+RTRIM(LTRIM(VV8_TIPVEI))+'.'+ZX4_CODLIN+'.'+RTRIM(LTRIM(VVR_GRUMOD)) AS 'ChaveClasseDeProduto' FROM VEI_CRM_PRODUTOS_CHASSI  
 UNION ALL  
 SELECT DISTINCT ' ' AS 'ChaveProdutoClasse',LTRIM(RTRIM(VV2_CODMAR)) + '#' + RTRIM(LTRIM(VV2_MODVEI)) AS 'ChaveProduto',
 'FAM.'+LTRIM(RTRIM(VV2_CODMAR))+'.'+RTRIM(LTRIM(VV2_TIPVEI))+'.'+ RTRIM(LTRIM(VVR_XLINHA)) + '.' + RTRIM(LTRIM(VVR_GRUMOD)) AS 'ChaveClasseDeProduto' 
 FROM VV2010 VV2 INNER JOIN VVR010 VVR ON VV2.VV2_CODMAR = VVR.VVR_CODMAR AND VV2.VV2_GRUMOD = VVR.VVR_GRUMOD WHERE  VV2.D_E_L_E_T_ = ' ' AND VV2.VV2_MSBLQL <> '1' 
 AND VVR.D_E_L_E_T_ = ' ' AND VVR.VVR_XLINHA <> ' '  ORDER BY  2  
 