SELECT  TOP 250 R_E_C_N_O_ FROM dbo.SE1010 WHERE D_E_L_E_T_ = ' ' 
AND (CHARINDEX(( '147468' ),CONVERT(CHAR(20),( E1_NUMBCO )))>0 ) ORDER BY E1_FILIAL DESC ,E1_PREFIXO DESC ,E1_NUM DESC ,E1_PARCELA DESC ,E1_TIPO DESC ,R_E_C_N_O_ DESC
