" SELECT  LANC.*, F4_OPEMOV 
 FROM    
    FAT_COMISSOES_GERA_LANC LANC 
    JOIN SF4010 F4 ON TES = F4_CODIGO AND F4.D_E_L_E_T_ = ' ' WHERE     F4_OPEMOV in ('05','98','16') AND
    TIPO_ORIGEM <> 'DEV' AND
    TIPO_ORIGEM <> 'ATD_PEC'  AND
    SUBSTRING(EMISSAO,1,6) = '202508' AND 
    FILIAL BETWEEN '01' AND '33'
   AND CODIGO_VEN <> '000000' 
 UNION ALL 
 SELECT  LANC.*, F4_OPEMOV 
 FROM    
    FAT_COMISSOES_GERA_LANC LANC
    JOIN SF4010 F4 ON TES = F4_CODIGO AND F4.D_E_L_E_T_ = ' ' WHERE     F4_OPEMOV = '29' AND
    TIPO_ORIGEM = 'DEV' AND
    SUBSTRING(EMISSAO,1,6) = '202508' AND 
    FILIAL BETWEEN '01' AND '33'
   AND CODIGO_VEN <> '000000' 
"
