//Bibliotecas
#Include "Protheus.ch"
 
/*--------------------------------------------------------------------------------------------------------------*
 | P.E.:  TK271ROTM                                                                                             |
 | Desc:  Ações Relacionadas da rotina de Call Center                                                           |
 | Link:  http://tdn.totvs.com/pages/releaseview.action?pageId=6787737                                          |
 *--------------------------------------------------------------------------------------------------------------*/
 
User Function NX271ROTM(aButtons)
   
aAdd( aButtons, {'Relacionar PA', 'U_XAG0087()', 0, 7})

Return aButtons
